In [ ]:
# For tips on running notebooks in Google Colab, see
# https://pytorch.org/tutorials/beginner/colab̵̵̵̵̵̵
%matplotlib inline

Tensors
=======

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model's parameters.

Tensors are similar to NumPy's ndarrays, except that tensors can run on
GPUs or other specialized hardware to accelerate computing. If you're
familiar with ndarrays, you'll be right at home with the Tensor API. If
not, follow along in this quick API walkthrough.


In [1]:
# TODO: Import torch and numpy
import torch
import numpy as np

Tensor Initialization
=====================

Tensors can be initialized in various ways. Take a look at the following
examples:

**Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.


In [2]:
data = [[1, 2], [3, 4]]
# TODO: Create a tensor from data
tensor = torch.tensor(data)

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see
`bridge-to-np-label`{.interpreted-text role="ref"}).


In [3]:
np_array = np.array(data)
# TODO: Convert NumPy array to tensor
numpy_tensor = torch.from_numpy(np_array)
numpy_tensor

tensor([[1, 2],
        [3, 4]])

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.


In [7]:
# TODO: Create a tensor of ones and a random tensor, then print them
ones_tensor = torch.ones(3,3)
rand_tensor = torch.rand_like(ones_tensor)
print("Ones Tensor:\n", ones_tensor)
print("Random Tensor:\n", rand_tensor)

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Random Tensor:
 tensor([[0.1511, 0.7365, 0.8594],
        [0.6502, 0.5240, 0.8609],
        [0.9318, 0.5680, 0.4217]])


**With random or constant values:**

`shape` is a tuple of tensor dimensions. In the functions below, it
determines the dimensionality of the output tensor.


In [8]:
# TODO: Initialize random, ones, and zeros tensors and print them
shape = (5,5)
t1 = torch.rand(shape)
t2 = torch.ones(shape)
t3 = torch.zeros(shape)
print("Random Tensor:\n", t1)
print("Ones Tensor:\n", t2)
print("Zeros Tensor:\n", t3)

Random Tensor:
 tensor([[0.6719, 0.3149, 0.9208, 0.7539, 0.3285],
        [0.6464, 0.8352, 0.5798, 0.3099, 0.1312],
        [0.0522, 0.4350, 0.4792, 0.1262, 0.8809],
        [0.1831, 0.7290, 0.6440, 0.5944, 0.4425],
        [0.0789, 0.0175, 0.0413, 0.9912, 0.8059]])
Ones Tensor:
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
Zeros Tensor:
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


------------------------------------------------------------------------


Tensor Attributes
=================

Tensor attributes describe their shape, datatype, and the device on
which they are stored.


In [9]:
# TODO: Create a random tensor and print its shape, dtype, and device
tensor = torch.rand(4,5)
print(f"Shape: {tensor.shape}")
print(f"Device: {tensor.device}")
print(f"Dtype: {tensor.dtype}")

Shape: torch.Size([4, 5])
Device: cpu
Dtype: torch.float32


------------------------------------------------------------------------


Tensor Operations
=================

Over 100 tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random sampling, and more are
comprehensively described
[here](https://pytorch.org/docs/stable/torch.html).

Each of them can be run on the GPU (at typically higher speeds than on a
CPU). If you're using Colab, allocate a GPU by going to Edit \> Notebook
Settings.


In [10]:
# TODO: Move tensor to GPU if available and print device
if torch.backends.mps.is_available():
  tensor = tensor.to('mps')
print(f"Device: {tensor.device}")

Device: mps:0


Try out some of the operations from the list. If you\'re familiar with
the NumPy API, you\'ll find the Tensor API a breeze to use.


**Standard numpy-like indexing and slicing:**


In [11]:
# TODO: Set all elements in the second column of a tensor to zero and print the tensor
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors** You can use `torch.cat` to concatenate a sequence of
tensors along a given dimension. See also
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining op that is subtly different from `torch.cat`.


In [14]:
# TODO: Concatenate tensors along dimension 1 and print the result
t1 = torch.rand(2,3)
t2 = torch.rand(2,3)
t3 = torch.cat([t1, t2], dim=1)
print("t1:\n", t1)
print("t2:\n", t2)
print("Concatenated t3:\n", t3)

t1:
 tensor([[0.1465, 0.6663, 0.3043],
        [0.2788, 0.5930, 0.7618]])
t2:
 tensor([[0.6402, 0.1609, 0.7743],
        [0.2349, 0.7186, 0.6843]])
Concatenated t3:
 tensor([[0.1465, 0.6663, 0.3043, 0.6402, 0.1609, 0.7743],
        [0.2788, 0.5930, 0.7618, 0.2349, 0.7186, 0.6843]])


**Multiplying tensors**


In [18]:
# TODO: Compute and print the element-wise product of a tensor
product_tensor = t1 * t2
product_tensor

tensor([[0.0938, 0.1072, 0.2356],
        [0.0655, 0.4261, 0.5213]])

This computes the matrix multiplication between two tensors


In [19]:
# TODO: Compute and print the matrix multiplication of a tensor and its transpose
matrix_mul_tensor = t1 @ t2.T
matrix_mul_tensor

tensor([[0.4366, 0.7215],
        [0.8638, 1.0129]])

**In-place operations** Operations that have a `_` suffix are in-place.
For example: `x.copy_(y)`, `x.t_()`, will change `x`.


In [20]:
print(tensor, "\n")
# TODO: Add 5 to all elements of a tensor in-place and print the tensor
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<div style="background-color: #54c7ce; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f1; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>

</div>



------------------------------------------------------------------------


Bridge with NumPy {#bridge-to-np-label}
=================

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.


Tensor to NumPy array
=====================


In [21]:
# TODO: Convert a tensor to a NumPy array and print both
nd_array = tensor.numpy()
print(f"{tensor}\n{nd_array}")

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
[[6. 5. 6. 6.]
 [6. 5. 6. 6.]
 [6. 5. 6. 6.]
 [6. 5. 6. 6.]]


A change in the tensor reflects in the NumPy array.


In [22]:
# TODO: Add 1 to the tensor in-place and print both the tensor and NumPy array
tensor.add_(1)
print(f"{tensor}\n{nd_array}")

tensor([[7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.]])
[[7. 6. 7. 7.]
 [7. 6. 7. 7.]
 [7. 6. 7. 7.]
 [7. 6. 7. 7.]]


NumPy array to Tensor
=====================


In [27]:
# TODO: Create a NumPy array and convert it to a tensor
rand_array = np.random.rand(2,3)
rand_tensor = torch.from_numpy(rand_array)
print(rand_array)
print(rand_tensor)

[[0.05280939 0.48600064 0.63536734]
 [0.91071668 0.89819015 0.74681082]]
tensor([[0.0528, 0.4860, 0.6354],
        [0.9107, 0.8982, 0.7468]], dtype=torch.float64)


Changes in the NumPy array reflects in the tensor.


In [29]:
# TODO: Add 1 to the NumPy array in-place and print both the tensor and NumPy array
rand_array += 1
print(rand_tensor)
print(rand_array)

tensor([[1.0528, 1.4860, 1.6354],
        [1.9107, 1.8982, 1.7468]], dtype=torch.float64)
[[1.05280939 1.48600064 1.63536734]
 [1.91071668 1.89819015 1.74681082]]
